import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "./useAuth";
import { useToast } from "./use-toast";
import { useTenantId } from "./useTenantId";

export interface Etiqueta {
  id: string;
  nome: string;
  slug: string;
  cor: string;
  icone: string;
  descricao?: string;
  ativa: boolean;
  escopo_modulos?: string[] | null;
  created_at: string;
  updated_at: string;
  grupo?: string;
}

export interface EtiquetaVinculo {
  id: string;
  etiqueta_id: string;
  referencia_tipo: string;
  referencia_id: string;
  created_at: string;
  etiqueta?: Etiqueta;
}

export const useEtiquetas = (ownerType?: string) => {
  const { user } = useAuth();
  const { tenantId } = useTenantId();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: etiquetas = [], isLoading } = useQuery({
    queryKey: ["etiquetas", ownerType],
    queryFn: async () => {
      let query = supabase
        .from("etiquetas")
        .select("*")
        .eq("ativa", true)
        .order("nome");

      // Se um ownerType for fornecido, filtra as etiquetas
      // Aceita etiquetas sem escopo OU que contenham o módulo no array escopo_modulos
      if (ownerType) {
        query = query.or(`escopo_modulos.is.null,escopo_modulos.cs.{"${ownerType}"}`);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as Etiqueta[];
    },
    enabled: !!user,
  });

  const createEtiqueta = useMutation({
    mutationFn: async (etiqueta: Partial<Etiqueta> & { nome: string }) => {
      const { data, error } = await supabase
        .from("etiquetas")
        .insert([{
          nome: etiqueta.nome,
          slug: '', // Will be auto-generated by trigger
          cor: etiqueta.cor || "#6B7280",
          icone: etiqueta.icone || "tag",
          descricao: etiqueta.descricao,
          escopo_modulos: etiqueta.escopo_modulos,
          user_id: user?.id,
        }])
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["etiquetas"] });
      toast({
        title: "Etiqueta criada",
        description: "A etiqueta foi criada com sucesso.",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Erro ao criar etiqueta",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const updateEtiqueta = useMutation({
    mutationFn: async ({ id, ...updates }: Partial<Etiqueta> & { id: string }) => {
      const { data, error } = await supabase
        .from("etiquetas")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["etiquetas"] });
      toast({
        title: "Etiqueta atualizada",
        description: "A etiqueta foi atualizada com sucesso.",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Erro ao atualizar etiqueta",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const deleteEtiqueta = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("etiquetas")
        .update({ ativa: false })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["etiquetas"] });
      toast({
        title: "Etiqueta removida",
        description: "A etiqueta foi removida com sucesso.",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Erro ao remover etiqueta",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const trocarEtiquetaDeGrupo = useMutation({
    mutationFn: async ({ 
      itemId, 
      modulo, 
      etiquetaAdicionarId, 
      grupo 
    }: { 
      itemId: string; 
      modulo: string; 
      etiquetaAdicionarId: string; 
      grupo: string 
    }) => {
      const { error } = await supabase.rpc('trocar_etiqueta_de_grupo', {
        p_item_id: itemId,
        p_modulo: modulo,
        p_etiqueta_adicionar_id: etiquetaAdicionarId,
        p_grupo: grupo,
      });

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['processos'] });
      queryClient.invalidateQueries({ queryKey: ['etiqueta_vinculos'] });
      toast({
        title: "Fase atualizada",
        description: "A fase do processo foi alterada com sucesso.",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Erro ao atualizar fase",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  return {
    etiquetas,
    isLoading,
    createEtiqueta,
    updateEtiqueta,
    deleteEtiqueta,
    trocarEtiquetaDeGrupo,
  };
};

export const useEtiquetaVinculos = (
  referenciaType: 'processos' | 'transacoes' | 'agendas' | 'contatos' | 'patrimonio' | 'documentos' | 'financeiro' | string, 
  referenciaId?: string
) => {
  const { user } = useAuth();
  const { tenantId } = useTenantId();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: vinculos = [], isLoading } = useQuery({
    queryKey: ["etiqueta_vinculos", referenciaType, referenciaId],
    queryFn: async () => {
      let query = supabase
        .from("etiqueta_vinculos")
        .select(`
          *,
          etiqueta:etiquetas(*)
        `)
        .eq("referencia_tipo", referenciaType);

      if (referenciaId) {
        query = query.eq("referencia_id", referenciaId);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as EtiquetaVinculo[];
    },
    enabled: !!user,
  });

  const addEtiqueta = useMutation({
    mutationFn: async ({ etiquetaId, referenciaId }: { etiquetaId: string; referenciaId: string }) => {
      if (referenciaType === 'processos') {
        const { data, error } = await supabase
          .from("processo_etiquetas")
          .insert({
            etiqueta_id: etiquetaId,
            processo_id: referenciaId,
            tenant_id: tenantId,
            user_id: user?.id,
          })
          .select()
          .single();
        
        if (error) throw error;
        return data;
      } else if (referenciaType === 'transacoes') {
        const { data, error } = await supabase
          .from("transacoes_financeiras_etiquetas")
          .insert({
            etiqueta_id: etiquetaId,
            transacao_id: referenciaId,
            tenant_id: user?.id,
          })
          .select()
          .single();
        
        if (error) throw error;
        return data;
      } else if (referenciaType === 'agendas') {
        const { data, error } = await supabase
          .from("etiqueta_vinculos")
          .insert({
            etiqueta_id: etiquetaId,
            referencia_tipo: 'agendas',
            referencia_id: referenciaId,
            user_id: user?.id,
          })
          .select(`
            *,
            etiqueta:etiquetas(*)
          `)
          .single();
        
        if (error) throw error;
        return data;
      } else {
        const { data, error } = await supabase
          .from("etiqueta_vinculos")
          .insert({
            etiqueta_id: etiquetaId,
            referencia_tipo: referenciaType,
            referencia_id: referenciaId,
            user_id: user?.id,
          })
          .select(`
            *,
            etiqueta:etiquetas(*)
          `)
          .single();

        if (error) throw error;
        return data;
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["etiqueta_vinculos"] });
      queryClient.invalidateQueries({ queryKey: ["processos"] });
      queryClient.invalidateQueries({ queryKey: ["agendas"] });
    },
    onError: (error: any) => {
      toast({
        title: "Erro ao adicionar etiqueta",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const removeEtiqueta = useMutation({
    mutationFn: async ({ etiquetaId, referenciaId }: { etiquetaId: string; referenciaId: string }) => {
      if (referenciaType === 'processos') {
        const { error } = await supabase
          .from("processo_etiquetas")
          .delete()
          .eq("etiqueta_id", etiquetaId)
          .eq("processo_id", referenciaId);
        
        if (error) throw error;
      } else if (referenciaType === 'transacoes') {
        const { error } = await supabase
          .from("transacoes_financeiras_etiquetas")
          .delete()
          .eq("etiqueta_id", etiquetaId)
          .eq("transacao_id", referenciaId);
        
        if (error) throw error;
      } else if (referenciaType === 'agendas') {
        const { error } = await supabase
          .from("etiqueta_vinculos")
          .delete()
          .eq("etiqueta_id", etiquetaId)
          .eq("referencia_id", referenciaId)
          .eq("referencia_tipo", 'agendas');
        
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from("etiqueta_vinculos")
          .delete()
          .eq("etiqueta_id", etiquetaId)
          .eq("referencia_id", referenciaId)
          .eq("referencia_tipo", referenciaType);

        if (error) throw error;
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["etiqueta_vinculos"] });
      queryClient.invalidateQueries({ queryKey: ["processos"] });
      queryClient.invalidateQueries({ queryKey: ["agendas"] });
    },
    onError: (error: any) => {
      toast({
        title: "Erro ao remover etiqueta",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  return {
    vinculos,
    isLoading,
    addEtiqueta,
    removeEtiqueta,
  };
};